remote_theme: ankitsultana/researcher@gem

title: Maksat Satybaldiev
url: "https://maksatsat.github.io/"
baseurl: ""
markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Build with jekyll"

sass:
  style: compressed
  sass_dir: _sass

nav:
  - name: "About"
    link: "./"
  - name: "CV"
    link: "cv_satybaldiev.pdf"
  - name: "Contact"
    link: "contact"
